### ISSUE TITLE
East Futuna coordinates

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#103]
Shouldn't East Futunan (east2447) be more like here: -14.278717, -178.137222 ?

Or.. am I misunderstanding something? Right now it's on Futuna island in Vanuatu, next to outlier Futuna-Aniwa.

**Comment by d97hah** [comment]
Indeed it should. Thanks, I've adjusted it for next version.

2017-05-23 15:09 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
Glad to be of help :).

I'm learning lots more about more oceanic languages by going through various samples from publications and talking to Andy loads, and I just happened to notice this.

**Comment by xrotwang** [comment]
issue should be at [clld/glottolog](https://github.com/clld/glottolog), the new (as of september last year) home of the Glottolog data.

**Comment by HedvigS** [comment]
Ok, check. I thought that was just for the web app. Now I know better.

**Comment by xrotwang** [comment]
[clld/glottolog3](https://github.com/clld/glottolog3) is for the web app.
