### ISSUE TITLE
Harvest the AUTOTYP references

### ISSUE THREAD

**Issue by SimonGreenhill** [clld/glottolog-data#104]
https://github.com/autotyp/autotyp-data/blob/master/bibliography/autotyp.bib

**Comment by xrotwang** [comment]
Good idea, wrong repo. Try clld/glottolog
Am 25.05.2017 10:59 schrieb "Simon J Greenhill" <notifications@github.com>:

**Comment by SimonGreenhill** [comment]
Oops. Opened [here](https://github.com/clld/glottolog/issues/92)
