### ISSUE TITLE
Chaozhou [chao1238] and Teochew [teoc1236] appears to be the same

### ISSUE THREAD

**Issue by c933103** [clld/glottolog-data#105]
The two name given for the two code are just two different romanization for same chinese characters, was there any particular reason behind the split?

**Comment by d97hah** [comment]
That's indeed an error, thanks for catching it. I've removed Teochew
[teoc1236] for next version and added Teochew as an alternative name for
Chaozhou [chao1238]. NB glottolog data is now curated on clld/glottolog,
this repo is obsolete.


2017-08-03 8:03 GMT+02:00 c933103 <notifications@github.com>:
