### ISSUE TITLE
This repos should be marked as inactive

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#108]
This repos is no longer active, right?

When you search for "Glottolog" sometimes you get here, and people might be fooled that it's the place to go.

**Comment by xflr6** [comment]
We have recently [updated the link on the website](https://github.com/clld/glottolog3/commit/2c212eae69912af48c3513b579361093103664ad) so search engines might need some time to pick up that.
Would you like to put together a PR updating `README.md` here accordinly?

**Comment by HedvigS** [comment]
@xflr6 I was just wondering what's up. You could either update the repos description, or make it private or something. It's probably not an issue, I've just noticed that there's two and was wondering what's up.
