### ISSUE TITLE
n.a. n.d.-entries

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#14]
There are  3,216 entries with the "name" n.a. n.d in the current version of Glottolog

2,174 of which appear to be refs to files in Alaska Native Language Archive.

Several of them have editors, but not authors, in their bibtex-entry. Some of them seem valuable and have information in other fields like bibtexkey etc, but this cannot be searched for by a regular user.

**Comment by xflr6** [comment]
n.a. -> $author or $editor or Anonymous in clld/glottolog3@7f4dbee61adf014609df69e2ac59bdee68741248 (duplicate with #42)
