### ISSUE TITLE
Why keep already identified copies?

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#15]
I take it that when an entry has a year that starts with "c" it means that they are copies of an already existing entry in hh? (There's only one entry offa hh with a year that starts with "c", and that's because there's already another identical hh-entry.)

I haven't checked thoroughly, but it seems like the non-hh entry has less information than the hh-entry. I assume it has some sort of transitional function, or just a way of keeping all refs from each provider. But perhaps for users it looks rather strange? If not removed, perhaps they could be hidden?

**Comment by xflr6** [comment]
remaining 'c' and '//' year fields fixed in e8ef8788fb66a20d9214c7214e99392f6677dea8
