### ISSUE TITLE
Duplicate, Perrin (2005) Des représentations du temps en wolof.

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#17]
Perrin, Lo&\iuml;c-Michel. 2005. Des représentations du temps en wolof. Paris :  Université Paris 7. vi+707. Paris: Université de Paris 7 -- Denis Diderot.

Perrin, Loic-Michel. n.d. Des représentations du temps en wolof. vi+707. Paris: Univ. (Paris, Denis Diderot, Diss., 2005).

Also: "Lo&\iuml;c-Michel".replace("Loic", "Lo&\iuml;c")

**Comment by xflr6** [comment]
[seems to be fixed in 2.4](http://glottolog.org/langdoc/complexquery?languoids=&publisher=&title=repr%C3%A9sentations&journal=&author=perrin&year=&editor=&address=)
