### ISSUE TITLE
\texthooktop{b} etc in titles

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#18]
Sometimes there is code going on in the titles as they are displayed on the site. I am well aware what the code does, but other users might be confused, and sometimes it makes it harder to find a source. In many cases there are duplicates with the characters appropriate rendered.

Here are some examples that I noticed last July, all of them are still there. There's more, but I can't search for only backslashes in titles anymore (why is that btw?).

Pius W. Akumbu and Esther P. Asonganyi (2010) "Language in contact: the case of the Ful\texthooktop{b}e dialect of Kejom (Babanki)" African Study Monographs 31. pp. 173-187

Alexandra Y. Aikhenvald (2007) "Classifiers in Multiple Environments: Baniwa of {Içana/Kurripako{\textemdash}A} North Arawak Perspective" International Journal of American Linguistics 73. pp. 475{\textendash}500.

Alfonso García and Jürg Gasché (2007) "Ñek?rofe lletarafue {\textendash} El consejo de la chambira, vol. 2: anotaciones lexicales y gramaticales al texto huitoto (dialecto buue)". : IIAP.

Alina Jabłońska (1957) "J\textpolhook{e}zyk mieszany Chińsko-Rosyjski w Mandžurii" Przegl\textpolhook{a}d Orientalistyczny 2. pp. 157-168.

Antonia I. Koval{\textasciiacute} (1987) "O zna{\textthreequarters}cenii morfogi{\textthreequarters}ckogo pokazatelja klassa v fula" in N.V. Oxotina (ed) Morfonologija i morfologija klassov slov v jazykax Afriki. pp. 5–100. : Nauka.

Berger, Hermann (1967) "Review of Pinnow, {\germ<Kharia-Texte>}" Zeitschrift der Deutschen morgenländischen Gesellschaft 61. pp. 428-9.

Bhattacharya, Vidhushekahra (1939) "{\tib Bhoṫa-prakāśa}: a Tibetan chrestomathy, with introduction, skeleton grammar, notes, texts and vocabularies". pp. lix, 578. : University of Calcutta.

Bielmeier, Roland (2004) "Shafer\textasciiacutes proto-West Bodish hypothesis and the formation of the Tibetan verb paradigms" in Saxena, Anju (ed) Himalayan Languages: Past and Present. pp. 395-412.

Blood, Henry F. and Blood, Evangeline E. (1976) "Mnong R\;{o}l\;{o}m ethnographic texts". pp. 619. : Summer Institute of Linguistics.

Boutin, Pierre (1981) "Eléments pour une systématique du f\textopenond\oɔndhɔ̀, parler 'senoufo' du nord de la Côte d'Ivoire" Univ. de la Sorbonne Nouvelle (Paris 3).

Brigitte Pakendorf (2010) "Copied morphemes in Sakha and Ėven {\textendash} a comparison". Paper presented at the workshop Bound morphology in common: copy or cognate?, 43rd Annual Meeting of the Societas Linguistica Europaea, 2-5 September 2010, Vilnius University.

**Comment by xrotwang** [comment]
Numbers are up for Glottolog 2.6 - possibly due to new providers:
```
glottolog3=# select count(*) from source where title like '%\\%';
-[ RECORD 1 ]
count | 2470

Time: 1362.524 ms
glottolog3=# select count(*) from source where booktitle like '%\\%';
-[ RECORD 1 ]
count | 45
```

**Comment by HedvigS** [comment]
These are all/most from the TIPA-package, right? Stupid question: what's the method of rendering these characters with the text-encoding on the clld-apps?
