### ISSUE TITLE
Merge jiar1239 into jiar1240

### ISSUE THREAD

**Issue by xflr6** [clld/glottolog-data#40]
![clipboard01](https://cloud.githubusercontent.com/assets/6342379/5046028/81f91eb4-6c05-11e4-8115-aae23069b46f.png)

**Comment by xflr6** [comment]
prepared in clld/glottolog3@2b7a559dce6b4042c37b58d26b9256b2f1274, what about [Sidaba](http://glottolog.org/resource/languoid/id/sida1238): where to put, promote to a language?

**Comment by d97hah** [comment]
Sidaba shd be synonymous with the node Zbu-Tshobdun?! So alternative name
for Zbu-Tshobdun (or vice versa).

2015-04-10 15:09 GMT+02:00 Sebastian Bank <notifications@github.com>:

**Comment by xflr6** [comment]
Sidaba is currently a dialect and Zbu-Tshobdun a subfamily: Do you mean that there is no such dialect (or language) as Sidaba?

**Comment by d97hah** [comment]
Ok then it refers to Sidaba rGyalrong which is a variety of Caodeng which
is a variety of Zbu [NOCODE_Zbu]

2015-04-10 23:53 GMT+02:00 Sebastian Bank <notifications@github.com>:
