### ISSUE TITLE
Duplicate of Ka (1994) Wolof phonology and morphology"

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#5]
Ka, Omar (c1994) "Wolof phonology and morphology". pp. 151. Lanham: Univ. Press of America.

and 

Ka, Omar (1994) "Wolof phonology and morphology". pp. 151. Lanham: Univ. Press of America.

**Comment by xflr6** [comment]
[seems to have been fixed](http://glottolog.org/langdoc/complexquery?languoids=&publisher=&title=Wolof+phonology&journal=&author=&year=&editor=&address=)
