### ISSUE TITLE
Alternative name to Port Vato

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#57]
I think Port Vato (port1286) is also known as "Daakiye" and "Daakie", and it would seem that Harald has been agreeing with that because a ref with that name in the title has been tagged with that code.

**Comment by d97hah** [comment]
Fixed for next ver!

2015-01-12 18:02 GMT+01:00 Hedvig Skirgård <notifications@github.com>:

**Comment by xrotwang** [comment]
@d97hah When you say fixed for next version, shouldn't there be a commit/push of these changes in `languoids/lff.txt`?

**Comment by d97hah** [comment]
Should be and there is now!

2015-01-13 11:22 GMT+01:00 Robert Forkel <notifications@github.com>:

**Comment by xrotwang** [comment]
Yes! [That](https://github.com/clld/glottolog-data/commit/52244b603374d40f0b1c20ed114de760980ac3ce)'s what we want to see!
