### ISSUE TITLE
downloading tables

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#58]
I have gotten word that people would like to be able to download more information from the site, in particular the ENTIRE bibliography (sic) as it is currently displayed and all information in the "languages" tables. Currently one only gets 2000 lgs when one downloads the languages tables, and not the ISOs.

Perhaps it could be divided up into different tables and files somewhere under a little download-tab?

Sorry for creating more work, I just heard it from several people now so I thought I'd share. Also, I should add that people really, really, really like glottolog. Like, a lot.

Greetings from Paris

**Comment by d97hah** [comment]
Can't you download the entire bibio on http://glottolog.org/meta/downloads?
Or you mean the entire biblio formatted as a table?

2015-01-13 17:38 GMT+01:00 Hedvig Skirgård <notifications@github.com>:

**Comment by xflr6** [comment]
You can actually download the CSV of the languages (or any other) datatable in chunks by manipulating the url: Start with [this first one](http://glottolog.org/glottolog/language.csv?type=languages&sEcho=1&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&iDisplayStart=0&iDisplayLength=1000) and increase the number after `iDisplayStart=`:
[second](http://glottolog.org/glottolog/language.csv?type=languages&sEcho=1&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&iDisplayStart=1000&iDisplayLength=1000)
[third](http://glottolog.org/glottolog/language.csv?type=languages&sEcho=1&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&iDisplayStart=2000&iDisplayLength=1000)
[fourth](http://glottolog.org/glottolog/language.csv?type=languages&sEcho=1&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&iDisplayStart=3000&iDisplayLength=1000)
[fith](http://glottolog.org/glottolog/language.csv?type=languages&sEcho=1&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&iDisplayStart=4000&iDisplayLength=1000)
[sixth](http://glottolog.org/glottolog/language.csv?type=languages&sEcho=1&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&iDisplayStart=5000&iDisplayLength=1000)
[seventh](http://glottolog.org/glottolog/language.csv?type=languages&sEcho=1&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&iDisplayStart=6000&iDisplayLength=1000)
[last](http://glottolog.org/glottolog/language.csv?type=languages&sEcho=1&iSortingCols=1&iSortCol_0=0&sSortDir_0=asc&iDisplayStart=7000&iDisplayLength=1000)

There will be tutorials/recipes on stuff like this. Maybe you would like to contribute?

**Comment by HedvigS** [comment]
That's why the idea with a download tab seemed really familiar, sorry I should have known. 

The cvs- languages file just contains glottocode and glotto-name, the JSON contains longitude etc. Perhaps just adding a CSV file of that JSON would be sufficient?
The bibliography is indeed there in RDF and Bibtex. I guess... I don't know what other referencing apps people are using, but I known that most of them can integrate with bibtex smoothly. So, I'm gonna recumbent that.

**Comment by HedvigS** [comment]
@xrotwang  Uuuuuh cool! and good idea.

**Comment by xflr6** [comment]
As of 2.4, http://glottolog.org/meta/downloads has a CSV for all languoids with the full row set (same as the datatables CSV).
