### ISSUE TITLE
Reference for Kwak1264 [kwq] is not relevant

### ISSUE THREAD

**Issue by AliRob** [clld/glottolog-data#59]
There is no mention of Kwak in the paper referenced under Kwak1264:

Blench, Roger. 1999. Field trip to record the status of some little-known Nigerian languages. Ogmios. 11, 14.

**Comment by d97hah** [comment]
Yes there is "Bùkwák people from Kwak, speaking Kwak" p 1

2015-01-21 12:40 GMT+01:00 AliRob <notifications@github.com>:
