### ISSUE TITLE
Field consistency in hh17.txt/languages.yaml

### ISSUE THREAD

**Issue by xflr6** [clld/glottolog-data#63]
Is the `code+name` field for the new source format just denormalized (i.e. something wrong here)?
```python
>>> import yaml
>>> l = yaml.load(open('languages.yaml'))
>>> i = [v['code+name'] for v in l.itervalues()
         if v['code+name'] != '%s [%s]' % (v['name'], v['iso_639-3'])]
>>> print '\n'.join(sorted(i))
Betoi-Jirara [NOCODE_Betoi]
Birrdhawal [ihw]
Bukambero [lur]
Chairel [NOCODE_Chairel]
Jargon Loucheux [NOCODE_Jargon-Loucheux]
Southern Lalo [svl]
Tundra Nenets [yrk]
Yangliu [lly]
Yimas-Arafundi-Pidgin [NOCODE_Yimas-Arafundi-Pidgin]
```
Can we drop it to preclude such inconsitencies?

**Comment by d97hah** [comment]
Hi! We can drop it, the field is just there to allwo quicker searching and
copy-paste within the (original hh17.txt) file. alternatively it can be
kept but ignored for the purposes of glottolog-displaying.

2015-04-10 17:02 GMT+02:00 Sebastian Bank <notifications@github.com>:

**Comment by d97hah** [comment]
Ok recomputed at regular intervals from code and name. all the best, H

2015-04-10 23:39 GMT+02:00 Harald Hammarström <harald.hammarstrom@gmail.com>
:
