### ISSUE TITLE
Geo coordinates for Crimean tatar glottocode crim1257

### ISSUE THREAD

**Issue by Bibiko** [clld/glottolog-data#67]
I know, difficult, but since the majority of speaker lives on the Crimean peninsula (beside a large group in Uzbekistan) I'd argue to move this location to the Crimean peninsula (also due to the historic settlements)

long 34.08
lat 45

**Comment by d97hah** [comment]
thx fixed for next ver!

2015-05-05 19:10 GMT+02:00 Hans-Jörg Bibiko <notifications@github.com>:
