### ISSUE TITLE
Location of Portuguese is wrong

### ISSUE THREAD

**Issue by eric-muller** [clld/glottolog-data#69]
The location for Portuguese, ISO 639 por, is currently recorded as lat=42.03, lon=-4.19. That's actually in the middle of Spain. A better value is lat=39.91, lon=-8.10.

**Comment by d97hah** [comment]
Thanks, yes, we'd better put that one in Portugal (now fixed for next
version). We inherited most of these coordinates from other sources, which
as you can tell, was not unproblematic. Though whenever I check a
lesser-known lg, it seems to be correct most of the time. Thanks again, H

2015-06-30 4:01 GMT+02:00 eric-muller <notifications@github.com>:

**Comment by xrotwang** [comment]
@d97hah push it!
