### ISSUE TITLE
errors in Guugu Yimidhirr sources 

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#70]
1) in the desc stat browser the wrong sources is given as the most recent extensive grammar. It should be: Haviland, John. 1979. Guugu Yimidhirr. In Dixon, R.M.W. and Blake, Barry (eds.), Handbook of Australian Languages, 27-182. Amsterdam: John Benjamins.

But maybe that's just because it's old data in that version.

2) There are 4 publications by Levinson that are labeled as doctype "grammar" but that are not.

**Comment by d97hah** [comment]
Thx fixed for next version

2015-07-07 9:08 GMT+02:00 Hedvig Skirgård <notifications@github.com>:
