### ISSUE TITLE
refs wrongly assigned to Orma [orc]

### ISSUE THREAD

**Issue by HedvigS** [clld/glottolog-data#72]
Pejros, I. 1994. Some Problems of Austronesian Accent and *T *C (Notes of an Outsider). Oceanic Linguistics 33. 105-127.

has been assigned to Orma [orc] based on "outsider". There's a few more refs like that

Wyk, Egidius B. van. 1993. C. M. Doke: a critical review by a believing outsider. African studies 52. 21-33.

Headland, Thomas N. and Kenneth L. Pike and Marvin Harris. 1990. Emics and ethics: the insider/ outsider debate. Frontiers of Anthropology, vol. 7. Newbury Park: Sage Publications: Sage Publications.

Carol Myers-Scotton. 2007. Language Contact: Why Outsider System Morphemes Resist Transfer. Journal of Language Contact - THEMA 1. 21–41.

**Comment by d97hah** [comment]
Thx! Fixed for next ver

2015-08-29 23:41 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by xrotwang** [comment]
Fixed, see http://glottolog.org/resource/languoid/id/orma1241
