### ISSUE TITLE
Add Igneri and Vedda-Sinhala Creole?

### ISSUE THREAD

**Issue by grenadeforce** [clld/glottolog-data#73]
Igneri was an Arawak language. Island Caribs later displaced the Igneri, took their language and it developed into Island Carib.

The Vedda language predecessor to modern form of Vedda which retains little of the original language and is called Vedda-Sinhala creole.

**Comment by d97hah** [comment]
Both those lgs are already there

2015-09-12 4:07 GMT+02:00 grenadeforce <notifications@github.com>:

**Comment by grenadeforce** [comment]
No. There is Island Carib, not it's predecessor Igneri. There is "Vedda" but on the website the resources are only talking about Vedda-Sinhala Creole.

**Comment by d97hah** [comment]
Igneri and Island Carib are the same lg by the glottolog definition. There
is no other Vedda language attested than the Sinhala with Vedda lexical
items and accent. The earlier sources e.g. Seligmann contain lists of words
argued to pertain to the original Vedda language but that's an inference,
not an observation. By observation alone one cannot ascertain the existence
of a different Vedda lg, so it's not in Glottolog.

2015-09-12 14:26 GMT+02:00 grenadeforce <notifications@github.com>:
