### ISSUE TITLE
Mess with glottolog id and iso code — Low German vs (Nothern) Low Saxon.

### ISSUE THREAD

**Issue by iw2rmb** [clld/glottolog-data#76]
There is a https://en.wikipedia.org/wiki/Low_German page that refers to glottolog 'lowg1239' and iso639_3 'nds'.
SIL.org tells us that 'nds' iso code refers to 'Low German' and 'Low Saxon' names.
But the glottolog's 'nds' iso code refers to 'Northern Low Saxon' with different id — nort2627.

Please, point me how to solve this conflict?

**Comment by d97hah** [comment]
Hi Vitaly! The person who did the links on the WIkipedia page (have no idea
who) seems to have been in error in linking [nds] to lowg1239. The mapping
nort2627 to [nds] given on glottolog.org is the correct one, inasfar as
there can be a correct one. The [nds] iso-entry does not use the standard
name in the literature (see e.g.
Charles V. J. Russ 1990 The Dialects of modern German: a linguistic survey.
Routledge.
for the varieties it appear to intend to include (as per the listing in its
entry) and the opposition of this set of varieties vs the Dutch ones is not
a consistently motivated opposition. all the best, H

2015-10-18 23:07 GMT+02:00 Vitaly Kovalev <notifications@github.com>:

**Comment by iw2rmb** [comment]
Thank you!
