### ISSUE TITLE
A paper on Enets

### ISSUE THREAD

**Issue by olesyakhanina** [clld/glottolog-data#78]
Our paper
Khanina, Olesya and Shluinsky, Andrey. 2014. A rare type of benefactive construction: Evidence from Enets. Linguistics 52. 1391-1431. De Gruyter Mouton.
(featured here http://glottolog.org/resource/reference/id/410603)
studied both dialects of Enets, Forest Enets and Tundra Enets, as mentioned in the introductory section. It would be great if the system referred to it as dealing with Tundra Enets as well.
Thank you!

**Comment by d97hah** [comment]
Fixed for next version!

2015-11-05 10:37 GMT+01:00 olesyakhanina <notifications@github.com>:

**Comment by olesyakhanina** [comment]
Thank you!
