### ISSUE TITLE
Invalid line in subclassification justifications

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog-data#81]
There's an invalid line

```
\Xcite[228-235]{hvb \Xcite[228-235]{hvb vanBulck:Congo}
```

in the [subclassification justifications file](https://github.com/clld/glottolog-data/blob/master/languoids/forkel_subclassification_justifications-utf8.tab#L1008)

**Comment by d97hah** [comment]
Shd be fixed with new commit

2015-11-17 13:14 GMT+01:00 Robert Forkel <notifications@github.com>:
