### ISSUE TITLE
Location of Kamas is incorrect

### ISSUE THREAD

**Issue by piilusiil** [clld/glottolog-data#89]
Hi! I'd like to point out that the location of Kamas on the map is off quite a bit. The most correct location would be the village of Abalakovo in Krasnoyarsk krai where the speakers community settled down in the beginning of the 20th century

(https://www.openstreetmap.org/export#map=16/55.0684/94.8332&layers=N)

**Comment by d97hah** [comment]
Thanks, fixed for next version!

2016-06-24 17:03 GMT+02:00 piilusiil <notifications@github.com>:
