### ISSUE TITLE
reconcile languages with same name but different hid

### ISSUE THREAD

**Issue by xrotwang** [clld/glottolog-data#9]
An example is Central Bontoc, but there are potentially more:

    glottolog3=# select l.name, count(ll.hid) as c from language as l, languoid as ll where l.pk = ll.pk group by name order by c desc;

**Comment by xflr6** [comment]
With Glottolog 2.4:
```
       name                   ids                       hids
0      Dama  [dama1262, dama1267]         [NOCODE_Dama, dmm]
1     Ganai  [gana1268, gana1278]                 [ihw, unn]
2     Mango  [mang1398, mang1429]        [mge, NOCODE_Mango]
3    Nepali  [nepa1252, nepa1254]                 [nep, npi]
4     Ngala  [ngal1300, ngal1301]  [nud, NOCODE_Ngala-Barth]
5     Taita  [tait1247, tait1250]        [NOCODE_Taita, dav]
6      Vili  [vili1238, vili1239]         [vif, NOCODE_Vili]
7  Wagawaga  [waga1262, waga1268]                 [wgw, wgb]
8       Yao  [yaoa1239, yaoo1241]          [NOCODE_Yao, yao]
```

Updates do not automatically follow name changes,from `lff/lof.txt` so:

* rename dama1262 to [Dama (Sierra Leone)](https://github.com/clld/glottolog-data/blob/master/languoids/lof.txt#L950) and/or dama1267 to [Dama (Cameroon)](https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L2565)?
* rename gana1268 to [Birdhawal](https://github.com/clld/glottolog-data/issues/9#issuecomment-63078713) or [Birrdhawal](https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L8163) or [Bidhawal](http://www-01.sil.org/iso639-3/documentation.asp?id=ihw)?
* rename mang1429 to [Mango (China)](https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L9265)?
* remove hid `nep` from nepa1252, move its macrolanguage iso-code `nep` to [east1436](http://glottolog.org/resource/languoid/id/east1436) (what about alternative names/links/references?), deactivate it and let it be superseded by east1436?
* rename ngal1301 to [Ngala of Lake Chad](https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L121)?
* rename tait1247 to [Cushitic Taita](https://github.com/clld/glottolog-data/blob/master/languoids/lof.txt#L947)?
* rename vili1239 to [Vili of Ngounie](https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L1742)?
* remove `hid` wgw from waga1262, make it `spurious retired` and move it under [bookkeeping languoids](http://glottolog.org/resource/languoid/id/book1242)?
* rename yaoa1239 to [Yebarana](https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L5117)?

@d97hah some (all?) of the [renames you mentioned](https://github.com/clld/glottolog-data/issues/9#issuecomment-63078713) do not seem to be included in [hh17.txt](https://github.com/clld/glottolog-data/blob/master/languoids/hh17.txt) (and therefore in `languages.yaml`), is this a glitch?

**Comment by d97hah** [comment]
2015-04-10 16:42 GMT+02:00 Sebastian Bank <notifications@github.com>:

> With Glottolog 2.4:
>
>        name                   ids                       hids
> 0      Dama  [dama1262, dama1267]         [NOCODE_Dama, dmm]
> 1     Ganai  [gana1268, gana1278]                 [ihw, unn]
> 2     Mango  [mang1398, mang1429]        [mge, NOCODE_Mango]
> 3    Nepali  [nepa1252, nepa1254]                 [nep, npi]
> 4     Ngala  [ngal1300, ngal1301]  [nud, NOCODE_Ngala-Barth]
> 5     Taita  [tait1247, tait1250]        [NOCODE_Taita, dav]
> 6      Vili  [vili1238, vili1239]         [vif, NOCODE_Vili]
> 7  Wagawaga  [waga1262, waga1268]                 [wgw, wgb]
> 8       Yao  [yaoa1239, yaoo1241]          [NOCODE_Yao, yao]
>
> Updates do not automatically follow name changes,from lff/lof.txt so:
>
>    - rename dama1262 to Dama (Sierra Leone)
>    <https://github.com/clld/glottolog-data/blob/master/languoids/lof.txt#L950>
>    and/or dama1267 to Dama (Cameroon)
>    <https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L2565>
>    ?
>    - rename gana1268 to Birdhawal
>    <https://github.com/clld/glottolog-data/issues/9#issuecomment-63078713>
>    or Birrdhawal
>    <https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L8163>
>    or Bidhawal <http://www-01.sil.org/iso639-3/documentation.asp?id=ihw>?
>    - rename mang1429 to Mango (China)
>    <https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L9265>
>    ?
>    - remove hid nep from nepa1252, move its macrolanguage iso-code nep to
>    east1436 <http://glottolog.org/resource/languoid/id/east1436> (what
>    about alternative names/links/references?), deactivate it and let it be
>    superseded by east1436?
>    - rename ngal1301 to Ngala of Lake Chad
>    <https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L121>
>    ?
>    - rename tait1247 to Cushitic Taita
>    <https://github.com/clld/glottolog-data/blob/master/languoids/lof.txt#L947>
>    ?
>    - rename vili1239 to Vili of Ngounie
>    <https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L1742>
>    ?
>    - remove hid wgw from waga1262, make it spurious retired and move it
>    under bookkeeping languoids
>    <http://glottolog.org/resource/languoid/id/book1242>?
>    - rename yaoa1239 to Yebarana
>    <https://github.com/clld/glottolog-data/blob/master/languoids/lff.txt#L5117>
>    ?
>
>
All good!



>
>
> @d97hah <https://github.com/d97hah> some (all?) of the renames you
> mentioned
> <https://github.com/clld/glottolog-data/issues/9#issuecomment-63078713>
> do not seem to be included in hh17.txt
> <https://github.com/clld/glottolog-data/blob/master/languoids/hh17.txt>
> (and therefore in languages.yaml), is this a glitch?
>
It's a feature :-). [In my old setup] the lg-names in hh17.txt are not
significant, while the names in lff.txt are. Also the HH-classification in
hh17.txt is not significant (lff.txt is) and then there's the code+name
issue. Otherwise the fields of hh17.txt should be sifnificant. In our new
setup, maybe the insignificnt things should be taken out of languoids.yaml
or out of lff.txt, to avoid mixups. Whatever you prefer!

**Comment by xflr6** [comment]
What is the wanted spelling for the new name of gana1268 (see [above](https://github.com/clld/glottolog-data/issues/9#issuecomment-91579723)): Birdhawal or Birrdhawal or Bidhawal (if not the second, maybe update `lff.txt`)?

@haspelmath any concerns about the new names (parenthesis, use of 'of')? Rename both or maybe only the non-iso-code Dama?

**Comment by d97hah** [comment]
Birrdhawal is preferred!

2015-04-13 14:13 GMT+02:00 Sebastian Bank <notifications@github.com>:
