### ISSUE TITLE
Two subgroups labelled South Halmahera-West New Guinea

### ISSUE THREAD

**Issue by malcolm42** [clld/glottolog-data#90]
Just been going through the Austronesian part of the Newick file. A phenomenal and useful piece of work!
In the process, I noticed that South Halmahera-West New Guinea is the label for two groups. I assume this is an error.
I've checked the listed source, Dave Kamholz' PhD dissertation. The page refs take me to DK's discussion of previous literature, not DK's new subgrouping, but I can't figure out which part of DK's discussion the SHWNG bit of the Glottolog tree is based on.

Malcolm Ross

**Comment by d97hah** [comment]
Indeed, the outer one should be called Greater SHWNG, I've fixed that for
next version. Thanks for catching it.

2016-11-03 10:25 GMT+01:00 malcolm42 <notifications@github.com>:
