### ISSUE TITLE
Odd error in subgrouping under St George linkage [stge1234] (Austronesian)

### ISSUE THREAD

**Issue by malcolm42** [clld/glottolog-data#92]
The  Label-Bilur [labe1241] node superordinate to Patpatar-Minigir-Tolai [patp1244],Label [labe1239][lbb], Kandas-Duke of York [kand1307] and Bilur [bilu1244][bxf] is in the wrong place. Instead, Patpatar-Minigir-Tolai [patp1244], Label-Bilur [labe1241] (superordinate to Label [labe1239][lbb] and Bilur [bilu1244][bxf]) and Kandas-Duke of York [kand1307] should all be subordinate to St George linkage [stge1234] and coordinate with Konomala etc.

**Comment by d97hah** [comment]
Indeed, thanks for catching that, fixed for next version. all the best, H

2016-11-04 6:01 GMT+01:00 malcolm42 <notifications@github.com>:
