### ISSUE TITLE
Add new language: Elfdalian

### ISSUE THREAD

**Issue by matsbla** [clld/glottolog-data#93]
Elfdalian is a minority language of Sweden. It got assigned an ISO 639-3 code outside of the regular review process earlier this year. More documentation about the language and the issue can be found here:
http://www-01.sil.org/iso639-3/chg_detail.asp?id=2015-046&lang=ovd

**Comment by d97hah** [comment]
It's already in glottolog:
http://glottolog.org/resource/languoid/id/dale1238

2016-11-25 0:27 GMT+01:00 matsbla <notifications@github.com>:

**Comment by matsbla** [comment]
I don't think Elfdalian and Dalecarlian is the same. Elfdalian is sometimes considered as the most rare variant of Dalecarlian. Dalecarlian is mutual intelligible with Swedish, whereas Elfdalian is not. I don't think these are the same.

However, the litteratur provided in the entry seem correct, maybe just the name needs to be updated? And also the correct ISO639-3 code is now 'ovd'.

**Comment by matsbla** [comment]
From p, 8 - 12 here there is also an extensive overview of academic articles, dictionaries and similar:
http://www-01.sil.org/iso639-3/cr_files/PastComments/CR_Comments_2015-046.pdf

**Comment by d97hah** [comment]
On what basis are you claiming "Dalecarlian is MI with Swedish"? Standard
usage of the terms has Dalecarlian as a cover name for several dialects of
which Elfdalian is one. All those are very divergent from standard Swedish,
and typically intelligible to each other. Hence the entry should be
Dalecarlian rather than singling out Elfdalian.

2016-11-25 1:14 GMT+01:00 matsbla <notifications@github.com>:

**Comment by matsbla** [comment]
So it depends if Dalecarlian refers to what in Swedish is called 'Ovansiljanmål' or 'Damlål'? As far as I know the literature on the topic is scarce, but linguistics in the field I've spoken to say said that there is some MI within the 'Ovansiljanmål', but outside this group it becomes more difficult.

I do not have references, however the most of litterature in the entry at Glottolog only specifically describe Elfdalian, there are only 2 linguistic reference  from 1909 and 1925 that describe 'Dalmålet'. Would be interesting to see more literature supporting the claim that Dalecarlian ("Damål"?) as a whole should be considered as a language.

**Comment by matsbla** [comment]
It seems liks Elfdalian has now been added;
http://glottolog.org/resource/languoid/id/elfd1234

**Comment by HedvigS** [comment]
Hej Mats, pratar du svenska? Det kanske är lättare om vi snackar svenska istället, både och jag Harald är svenskar.

Or not, not sure if you do know swedish. Anyways, Glottolog has dialects and languoids. Dalecarlian is a languoud, Elfdalian is listed as a dialect of Dalecarlian. All languiods, families, groupings, branches, dialects and everything else you can think of in Glottolog has a code. I.e. the fact that a variety has a glottocode does NOT entail that it is a language/languoid. This is different from ISO 639-3

**Comment by matsbla** [comment]
Jeg snakker norsk =)

Thanks for explaning about the Glottolog system.
For myself I try work on some Geo-mapping of language and to me it would just be very helpful to have corresponding codes between Glottolog and ISO639 as possible. So no mater how you choose to classify Elfdalian - at least there is a code now!

About the name, I know Elfdalian has been named both Elfdalian and Övdalian (and even Elvdalian in some few cases) in English. However, that is something completely different than Dalecarlian, which describe something else than Elfdalian/Övdalian.

**Comment by HedvigS** [comment]
Aha, okej då förstår jag. Norska, svenska. Samma grej! Jag mejlar med Danskar och Norrmän ofta på svenska/norska/danska. Funkar bra.

Ofta är Glottologs lat/long per språk bättre än Ethnologue, Ethnologue kan ibland hamna ute i vattnet eller så. 

Har du sett University of Maryland's Langscape? Här är lite info om dom, och kartor och språk, som kan vara hjälpsamt!

http://humans-who-read-grammars.blogspot.com.au/2014/12/linguistic-diveristy-important-things.html

Min förståelse är densamma som Haralds, att på engelska så är "Dalecarlian" ett övergripande begrepp som innefattar flera variteter i älvdalen, inklusive vad som på Engelska kallas "elfdarlian". Menar du alltså att 

1) dom inte borde beskrivas tillsammans som ett "språk" ?
2) att det finns varieteter i gruppen "dalecarlian" som är ömsesidigt förståeliga med kringliggande svenska?

**Comment by matsbla** [comment]
Jeg har ikke sett dette Langscape før, takk for tips, spennende prosjekt! Er dette basert på data fra Glottolog?

Angående Dalmål (Dalecarlian?) og Älvdalsk, jeg vet ikke hvordan de best skal klassifiseres, men jeg har kun sett litteratur som beskriver Älvdalsk, og mange av kildene som står oppført under Dalmål i Glottolog omhandler egentlig Älvdalsk, så det kunne jo vært lurt å sortere litteraturen korret på kodene i Glottolog.

Selv har jeg bare hørt fra en lingvist at man muligens burde se elvdalsk og andre ovansiljanmål som ett språk, da det er typologiske forskjeller, men jeg vet at andre er uenige i dette. Det kan jo godt være at Älvdalsk rett og slett bare har blitt mer beskrevet enn andre ovansiljanmål;
http://www.dt.se/dalarna/mora/sprakforskare-vamhusmalet-har-hamnat-i-skymundan
Så må man jo kanskje også vurdere det faktum at älvdølingene har en sterk språkidentitet og svært aktiv språkdeterminisme med utvikling av eget alfabet, bøker, sanger, egen avis, osv.
Norsk og svensk er jo også ganske likt, men vi regner det jo som to språk uansett? Man må vel vurdere andre kriterier enn de lingvistiske.

Jeg har ikke hørt noen mene at dalmål som helhet burde klassifiseres som et språk. men jeg vet for lite!

**Comment by HedvigS** [comment]
Langscape verkar vara baserat på Ethnologue's polygoner plus annat. Det är lite oklart, och dom vill att man betalar för att få tag på hela datasettet. CLLD-sajter (WALS, APiCS, PHOIBLE osv) använder Glottologs koorinater, men langscape verkar använda något annat. Dessutom har inte Glottolog polygoner, bara punkter.

Jag tror jag tar och skickar ett meddelande till Östen ändå. Han är pensionerad nu och gillar att snacka forskning, vi får se vad han säger. Han vet väldigt mycket om mål i Dalarna :)

**Comment by HedvigS** [comment]
Förresten, bara så vi är tydliga. Jag undrar inte om det är lite förvirring om Dalecarlian på engelsk motsvara "älvdalska" eller "dalmål". Jag håller med, det finns svenska dialekter i dalarna som är helt förståeliga (jag känner folk där och vi prata obehindrat), men jag trodde alltid att Dalecarlian på engelsk bara täckte dom mer besynnerliga älvdalska varieterna..

**Comment by HedvigS** [comment]
Östen har svarat: 
I am answering in English so you can copy and paste to anyone concerned. The situation around Dalecarlian and Elfdalian is extremely messy. I have tried to sort things out in several articles, all in Swedish. I am attaching them to this message.  But there is also a section in my book "Grammaticalization in the North" (downloadable from Language Science Press) (pp. 22-24), pasted below:
 
"As noted in the quotation from Wessén (1966) on page 27 above, the vernaculars spoken in Upper Dalarna (Övre Dalarna), the northern part of the province of Dalarna (latinized name: Dalecarlia), have a "special position" in differing more radically from the standard languages than perhaps any Scandinavian variety and in also being extremely diverse internally. In Swedish dialectology, these vernaculars are usually referred to as dalmål or egentligt dalmål 'Dalecarlian proper'. Confusion arises from the fact that the word dalmål is for most Swedes associated with the characteristic accent of speakers from the southern part of the province, which belongs to the Central Swedish mining district referred to as Bergslagen. The traditional vernaculars of this part of Dalarna are referred to in the dialectological literature as Dala-Bergslagsmål. The term "Dalecarlian" will be used in this work to refer to 'Dalecarlian proper', that is, the traditional vernaculars of the 21 parishes of Upper Dalarna. It should be borne in mind, however, that even though Dalecarlian as a whole has been assigned the status of a language in Ethnologue (www.ethnologue.com), the characterization given by the foremost expert on Dalecarlian, Levander (1928: 257), is more apt: "Dalecarlian is not one language…but rather a whole world of languages" – the parish varieties are often not mutually understandable, and the differences between villages in one and the same parish can be quite significant.  Commonly, the Dalecarlian area is divided into three parts – Ovansiljan, Västerdalarna and Nedansiljan (see Map 6), but the actual picture is somewhat more complex. Map 7 is based on a lexical comparison between vernaculars in Dalarna described in more detail in Dahl (2005). It shows that the varieties that differ most from the others (and from Standard Swedish) are found in Ovansiljan (except Ore) and northern Västerdalarna (Transtrand and Lima), these forming two fairly well delineated areas. Within Ovansiljan, the vernaculars in Älvdalen and Våmhus form a highly distinctive subarea, and Orsa also stands out as having many specific traits. Within Nedansiljan, Boda and Rättvik make up an area of their own, although it differs less dramatically from the neighbours to the south. The rest of Dalarna, including the remaining parts of Västerdalarna and Nedansiljan, is most properly regarded as a dialect continuum without clear borders. The parishes of Särna and Idre in the northern tip of the province, however, belonged to Norway until 1645 and the vernaculars there are very different from Dalecarlian, being quite similar to the Norwegian vernaculars on the other side of the border."
The maps referred to can be found in the article “Att sätta älvdalskan på kartan” (Map 6=Karta 1.1, Map 7=Karta 3.1). As noted in the text, there is also great variation within the parishes - Elfdalian is spoken in 12 villages, each of which has a distinguishable dialect. The upshot is that we could afford language status on at least four levels: to Dalecarlian, as was done in earlier versions of Ethnologue, to the Ovansiljan varieties, to the varieties of Älvdalen (i.e. Elfdalian) and Våmhus, or to Elfdalian alone. From the dialectological point of view I think it might make most sense to see Ovansiljanmål as one language with a number of varieties. But from the socio-political point of view, things are a bit different. Elfdalian is just a lot more salient than the rest of Dalecarlian. This is based in linguistic reality in that it is the most distinct variety relative to Standard Swedish, both in that its internal development has taken it farthest away and in that it has most stubbornly resisted recent external influence. Furthermore, it probably has more active speakers than most other varieties, and most importantly, there is a strong movement supporting it as a separate language, with demands for minority language status, use in preschools, public signage etc. And recently it has become internationally famous as the assumed Viking language recently discovered to be spoken in the deep forests of Sweden (this of course is an "alternative fact").
I strongly suspect that this messy situation, with complications both at the linguistic and the socio-political level, is not unique. I do not know if there are any general principles at Glottolog for how such situations should be handled. My impression was that the term "languoid" was introduced to avoid the difficulties connected with the distinction between "languages" and "dialects". But now it seems that it is no less problematic.

Best,
Östen

**Comment by HedvigS** [comment]
Perhaps this discussion of "languoid" would interest @haspelmath

**Comment by matsbla** [comment]
Thanks for forwarding the email!

>  Dalecarlian as a whole has been assigned the status of a language in Ethnologue (www.ethnologue.com)

This was only true until about 2005/2006 when the Ethnologue codes were standardized as ISO639-3 and this code was removed after protest from Swedish government. So just to be clear; today Dalecarlian is not listed as a language in Ethnologue.

**Comment by HedvigS** [comment]
Övdalian [ovd] existerar just nu som ett språk i Ethnologue. Den gamla ISO 639-3 var [qer] om jag förstått rätt.

**Comment by HedvigS** [comment]
Såå... det låter lite som att Glottologen skulle kunna behöva innehålla en lite snävare definition än "Dalecarlian" men att Glottokoden skulle kunna bestå och länkas till [ovd] istället för till [qer]. Det är en lösning, till exempel.

**Comment by matsbla** [comment]
Övdalian is the same as Elfdalian (Älvdalska). As mentioned earlier different terms are used in English to describe Älvdalska.
Övdalian [ovd] is not the same as Dalecarlian ("dalmål" or ""det egentlige dalmål")
Dalecarlian did have a code earlier, but it was removed. Then Övdalian was introduced last year which describe something else then Dalecarlian.
It is not the same.


Övdalian (Älvdalska) == Elfdalian
Övdalian is not Dalecarlian ("Dalmål" eller "det egentlige dalmål")!
As I mentioned, and as Östen repeats,

**Comment by HedvigS** [comment]
I know it's not the same :) I'm just saying, there is a listing for a related language / a language in the geography that has a clear relation to the previous.

**Comment by HedvigS** [comment]
And, "qer" would appear to be the old code since a) it's what glottolog points to and b) it's reserved for local use in the iso 639-3 list.

**Comment by matsbla** [comment]
Okay then we are on the same page! :)
The old code for Dalecarlian was **dlc**.
Within ISO639-3 the codes **qaa–qtz** are reserved for private use so **qer** is a private use tag code.

Will it not become even more confusing if both **elfd1234**" and **dale1238** will be pointed to **ovd**? Besides **dale1238** includes also Orsamål and Sollerömål, whereas **ovd** does not.

**Comment by HedvigS** [comment]
Another suggestion is to promote elfd1234 to languoid and dale1238 to a node for a group including elfd1234.

It's all up to @d97hah I think we've provided enough material for him and the other Glottolog editors to make a ruling.

**Comment by d97hah** [comment]
d97hah already had all this information and already made the ruling you now
see in Glottolog. Is there anything wrong with it?

2017-04-05 9:28 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
Depends on what the criteria for being a languoid are.

**Comment by oesten** [comment]
Here are links to two of my articles in Swedish:
http://www.ling.su.se/polopoly_fs/1.20598.1308862234!/menu/standard/file/Dahl_alvdalskan.pdf
http://spraktidningen.se/artiklar/2008/11/alvdalska-eget-sprak-eller-varsting-bland-dialekter

**Comment by HedvigS** [comment]
(Vi kan alltså forsätta på norsk-svenska om ni vill, eller inte. I vilket fall, god kväll :) )

**Comment by d97hah** [comment]
Do I have to explain that? A languoid is a term that is neutral to the
level or grouping of varieties, i.e., it can refer to a variety that is an
idiolect, varieties of a single village, a set of villages, a set of
mutually intelligible varieties, a family of mutually unintelligible
varieties and so on. Now that you know this, can you tell me there's
anything wrong with the current Glottolog treatment of Dalecarlian?

2017-04-05 10:21 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
I'm sorry, I was only trying to be helpful and bring the question to what I thought was it's core. I think there's a confusion often here as to what it takes to be listed as a dialect or a languoid, hence questions like Mats. If people expect Glottolog to list things as languoids only if they're not MI with something else, than according to what Mats and Östen have been saying it makes more sense to list it as a higher level grouping.

My experience is that this is a common misunderstanding between Glottolog and Ethnologue and iso 639-3. I was only trying to make that clearer. Apologies for upsetting you.

**Comment by d97hah** [comment]
It obviously does not help to produce a lot of email traffic with vague
pointers that something needs to be done. If you want to help, read about
the terms you are using and read the literature e.g. Glottolog cites for
its treatment and then state clearly what the disease and remedy is and
why. For example, from what Mats and Östen have been saying (Mats doesn't
know about the intelligibility status between different Dalecarlian
varieties and Östen's papers or quotes do not deal will intelligibility
systematically). Although you can find quotes in the literature that the
some Dalecarlian varieties are only with difficulty intelligible, there are
also quotes to the contrary, and most claims of (un)intelligibility are
vague as to the degree of intelligibility ("somehwat difficult"), the exact
parishes for which the claim is made and the source of the claim. (The
lexical differences are consistent with them being intelligible, though
that is not a sufficient requirement.) Glottolog does indeed use
intelligibility for any updates to the current inventory in what concerns
the status of a languoid (language vs dialect). In any case Glottolog
contains a complete mapping to Ethnologue, definitions and sources for
everything anyone can judge for him/herself. Confusions about this usually
arises from the fact that most confused people do not take the time to read
the definitions or the sources.

2017-04-05 10:47 GMT+02:00 Hedvig Skirgård <notifications@github.com>:

**Comment by HedvigS** [comment]
Please, take it easy. I'm leaving now.

**Comment by oesten** [comment]
I am afraid there is still some confusion. It seems from what @d97hah said that any node in Glottolog is also a languoid -- actually what I thought until today. But is @HedvidS saying that languoids have a special status? About the current Glottolog treatment of Dalecarlian: if Dalecarlian is synonymous to "det egentliga dalmålet", as in my book, and I think in earlier versions of Ethnologue, then it is not generally true that "Dalecarlian (of which there are some varieties) is not intelligible to Swedish [swe] and thus merits a separate entry". Many varieties that are considered as "egentligt dalmål" are fairly easily understandable to outsiders. I spent many summers in Leksand, which is part of the Dalecarlian area, so I think I have the requisite knowledge about this. I think the strongest argument for considering Dalecarlian a separate entity is that dialectologists have traditionally treated it as one. But the borderlines are quite fluid.

**Comment by d97hah** [comment]
Ok let me clear a few things up then, in Glottolog:
* Languoid is indeed the term that is neutral to level, as you correctly
thought (until today and hopefully beyond today)
* Every languoid also has exactly one level: family, language, and dialect
- There is a theoretically coherent definition of language based solely on
mutual intelligibility (email me for details), which is used for any
updates to the inventory, but only at some point in the future this will be
consistently applied across all varieties. There will still be practical
issues until the end of time, however.
- A family is a set of languages (all the direct children have to be
language-level languoids)
- There is no theoretically coherent definition of dialect beyond what's
required for being an idiolect and being part of a language. The inventory
of dialects in Glottolog is thus incomplete both in theory and practice.
But some aspects of the inventory are "conventional".

* Likely HedvigS wrote languoid when she meant to write language-level
languoid

* The theoretical definition of language used does not mean that every pair
of varieties that are part of different languages cannot be intelligible.
It does however mean that there must be at least one pair of varieties from
the two different languages which are not intelligible.

* What this means for Dalecarlian is that since some varieties of
Dalecarlian [qer] are not intelligible to some varieties of Swedish [swe],
[qer] and [swe] have to be different language-level languoids. The
intelligibility situation is judged so in Glottolog resting on numerous
observations in the literature and (I think) also Östen's experience, even
if those varieties in Leksand are not the ones the make it true.

* As concerns Glottolog, considering something a separate *entity* (I often
use the term variety) is almost trivial -- most idiolects could count as
such -- and a dialectological tradition would not be required








2017-04-05 15:52 GMT+02:00 Östen Dahl <notifications@github.com>:

**Comment by matsbla** [comment]
These references are marked as Dalecarlian, but they are about Elfdalian, maybe this should be updated?
- http://glottolog.org/resource/reference/id/474383
- http://glottolog.org/resource/reference/id/64019
- http://glottolog.org/resource/reference/id/475265
- http://glottolog.org/resource/reference/id/478162
- http://glottolog.org/resource/reference/id/505765
- http://glottolog.org/resource/reference/id/7956
- http://glottolog.org/resource/reference/id/44772
- http://glottolog.org/resource/reference/id/403599
- http://glottolog.org/resource/reference/id/505767
- http://glottolog.org/resource/reference/id/469806
- http://glottolog.org/resource/reference/id/314553

**Comment by d97hah** [comment]
Unfortunately references (for the entire glottolog) are only systematically
linked to language-level languoids, even when it's clear that a finer match
is possible. Though at some point in the future, there'll also be a
systematic mapping to dialect-level languoids, and only at that time
Elfdalian also will be updated accordingly...

2017-04-06 2:34 GMT+02:00 matsbla <notifications@github.com>:
