### ISSUE TITLE
Mono (Solomon Islands) is Mono-Alu in the literature

### ISSUE THREAD

**Issue by malcolm42** [clld/glottolog-data#94]
A minor matter. 'Mono (Solomon Islands)' (mono1273) is named Mono-Alu in the literature. The naming here is odd, as one of the dialects of Mono-Alu is (correctly) 'Mono' (mono1274). So replace  label 'Mono (Solomon Islands)' with label 'Mono-Alu'. Malcolm Ross.

**Comment by d97hah** [comment]
Thx adjusted for next version

2016-12-03 0:05 GMT+01:00 malcolm42 <notifications@github.com>:
