### ISSUE TITLE
360+ latitude conversion

### ISSUE THREAD

**Issue by agricolamz** [clld/glottolog-data#95]
Hi there!

I tried to map all languages by area ([here is a corrected result](https://agricolamz.github.io/families_by_area/)). But in some areas languages appear in different part of the map. It can be simply fixed by adding 360 to existing longitude.

| language               | glottolog   | my_correction |
|------------------------|-------------|---------------|
| Rakahanga-Manihiki     | -161        | 199           |
| Rarotongan             | -158        | 202           |
| Rapanui                | -109.34249  | 250.65751     |
| Pitcairn-Norfolk       | -130.08     | 229.92        |
| Mangareva              | -134.97034  | 225.02966     |
| South Marquesan        | -138.97893  | 221.02107     |
| North Marquesan        | -140.10792  | 219.89208     |
| Tuamotuan              | -140.6576   | 219.3424      |
| Old Rapa               | -144.33752  | 215.66248     |
| Tahitian               | -149.450226 | 210.549774    |
| Austral                | -149.46195  | 210.53805     |
| Hawaiian               | -155.42995  | 204.57005     |
| Penrhyn                | -157.9912   | 202.0088      |
| Pukapuka               | -165.58     | 194.42        |
| Niuean                 | -170.12     | 189.88        |
| Tokelau                | -171.816101 | 188.183899    |
| Samoan                 | -171.83     | 188.17        |
| Niuatoputapu           | -173.74249  | 186.25751     |
| Tonga (Tonga Islands)  | -175.25     | 184.75        |
| 'Niuafo'ou'            | -175.63991  | 184.36009     |
| Wallisian              | -176.207027 | 183.792973    |
| East Futuna            | -178.17     | 181.83        |
| Lauan                  | -178.78541  | 181.21459     |
| Central Siberian Yupik | -170.27166  | 189.72834     |
| Naukan Yupik           | -171.7554   | 188.2446      |
| Sirenik Yupik          | -173.925    | 186.075       |

**Comment by xrotwang** [comment]
I think there is no right or wrong here. It's just a matter of convention - and from my experience so far, keeping longitudes limited to the interval [-180, 180] seems to be more common. The leaflet library has an option to display markers on all "copies" of the world, called [`worldCopyJump`](http://leafletjs.com/reference.html#map-worldcopyjump), which may fix this problem for your map.

**Comment by agricolamz** [comment]
https://stackoverflow.com/questions/33522495/multiple-copies-of-the-world-when-zooming-out-in-worldmap-created-with-leaflet-i

Here is solution for an R users.
