### ISSUE TITLE
Location of Modern Georgean is wrong

### ISSUE THREAD

**Issue by agricolamz** [clld/glottolog-data#96]
Hi there!

The location of Modern Georgian (iso 639 kat) is reported as lat=39.37, long=45.81. It is better not to show it to Georgians. 41.850397, 43.786130 seems better.

**Comment by d97hah** [comment]
I've adjusted it accordingly for next version

2017-01-27 4:31 GMT+01:00 George Moroz <notifications@github.com>:

**Comment by agricolamz** [comment]
Thank you!
