### ISSUE TITLE
Location of Muslim Tat and others is little bit … wet

### ISSUE THREAD

**Issue by agricolamz** [clld/glottolog-data#97]
The location of Muslim Tat (iso 639 ttt) is reported as 38.87, 49.34. It is possible for them to be there, but...
Some other Sirens speaks:

- [Kalo Finnish Romani](http://glottolog.org/resource/languoid/id/kalo1256)
- [Baharna Arabic](http://glottolog.org/resource/languoid/id/baha1259)
- [Southern Balochi](http://glottolog.org/resource/languoid/id/sout2642)
- [Vietnamese](http://glottolog.org/resource/languoid/id/viet1252)
- [Malaccan Creole Malay](http://glottolog.org/resource/languoid/id/mala1482)
- [Plautdietsch](http://glottolog.org/resource/languoid/id/plau1238) (I'm not really sure that it is a good location)
- [Wayuu](http://glottolog.org/resource/languoid/id/wayu1243)

**Comment by d97hah** [comment]
I've adjusted it for next version

2017-01-27 4:42 GMT+01:00 George Moroz <notifications@github.com>:

**Comment by agricolamz** [comment]
Thank you!
