### ISSUE TITLE
Incorrect attribution for 3 Waorani references

### ISSUE THREAD

**Issue by simonsg** [clld/glottolog-data#99]
One of my colleagues who knows the Waorani situation well, has observed that three of the references in the Glottolog bibliography for the langauge are attributed to the wrong author.  The details are in the attached docx file.

[Patzelt or Peeke (1).docx](https://github.com/clld/glottolog-data/files/832203/Patzelt.or.Peeke.1.docx)

**Comment by d97hah** [comment]
Thanks Simonsg,
I've fixed that for next version (the problem arose through imperfect
parsing of fabre's biblio where Patzelt is just before Peeke
alphabetically). all the best, H

2017-03-09 21:29 GMT+01:00 simonsg <notifications@github.com>:
